[package]
name = "petri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.137"
serde-xml-rs = "0.5.1"
serde_derive = "1.0.137"
bitvec = "1.0.0"
thiserror = "1.0.31"
bimap = "0.6.2"
