[package]
name = "parity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
itertools = "0.10.3"
log = "0.4.17"
nom = "7.1.1"
petgraph = "0.6.2"
